pipeline{
    agent { label 'lmctl '}
    stages{
        stage('onboard docker-network'){
            steps{
				sh "lmctl env list"
				sh "lmctl project push testing"               
            }
        }
        stage('test docker-network'){
            steps{
                sh "lmctl project test testing"
            }
        }
        stage('package docker-network'){
            steps{
                sh "curl -v -u admin:admin123 --upload-file ./_lmctl/_build/docker-network-1.0.tgz http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/docker-network/"              
            }
        }
    }
}