pipeline{
    agent { label 'lmctl '}
    stages{
        stage('fetch and onboard dependencies'){
            steps{
				sh "lmctl env list"
				sh "wget http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/docker-network/docker-network-1.0.tgz"
				sh "lmctl pkg push docker-network-1.0.tgz testing" 
				sh "wget http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/ip-pbx/ip-pbx-1.0.tgz"
				sh "lmctl pkg push ip-pbx-1.0.tgz testing" 
				sh "wget http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/sip-performance/sip-performance-1.0.tgz"
				sh "lmctl pkg push sip-performance-1.0.tgz testing" 				
            }
        }	    
        stage('onboard hello-world'){
            steps{
				sh "lmctl project push testing"               
            }
        }
        stage('test hello-world'){
            steps{
                sh "lmctl project test testing"
            }
        }
        stage('package hello-world'){
            steps{
                sh "curl -v -u admin:admin123 --upload-file ./_lmctl/_build/hello-world-1.0.tgz http://$NEXUS_SVC_NODEPORT_SERVICE_HOST:$NEXUS_SVC_NODEPORT_SERVICE_PORT_NEXUS_HTTP/repository/raw/hello-world/"              
            }
        }
    }
}